CRUDContatos/Controllers/AlterarSenhaController.cs
using CrudContatos.Helper;
using CrudContatos.Models;
using CrudContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace CrudContatos.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;

        public AlterarSenhaController(IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                alterarSenhaModel.Id = usuarioLogado.Id;

                if (ModelState.IsValid)
                {
                    _usuarioRepositorio.AlterarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    return View("Index", alterarSenhaModel);
                }

                return View("Index", alterarSenhaModel);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possível alterar a sua senha, tente novamente. Detalhes do erro: {erro.Message}";
                return View("Index", alterarSenhaModel);
            }
        }
    }
}

CRUDContatos/Views/AlterarSenha/Index.cshtml
@using CrudContatos.Enums;
@model AlterarSenhaModel

@{
    ViewData["Title"] = "Alterar senha do usuário";
}

<div class="text-center">
    <h1 class="display-4">Alterar senha do usuário:</h1>
</div>

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<form asp-controller="AlterarSenha" asp-action="Alterar" method="post">

    <div class="form-group">
        <label for="senhaAtual">Senha Atual</label>
        <input type="password" asp-for="SenhaAtual" class="form-control" placeholder="Digite a senha atual do usuário.">
        @Html.ValidationMessageFor(sa => sa.SenhaAtual)
    </div>

    <div class="form-group">
        <label for="novaSenha">Nova Senha</label>
        <input type="password" asp-for="NovaSenha" class="form-control" placeholder="Digite a nova senha do usuário.">
        @Html.ValidationMessageFor(ns => ns.NovaSenha)
    </div>

    <div class="form-group">
        <label for="confirmarSenha">Confirme a senha</label>
        <input type="password" asp-for="ConfirmarNovaSenha" class="form-control" placeholder="Confirme a nova senha escolhida para o usuário">
        @Html.ValidationMessageFor(cs => cs.ConfirmarNovaSenha)
    </div>

    <br />
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Alterar senha</button>
        <a class="btn btn-secondary btn-block" asp-controller="Home" asp-action="Index" role="button">Voltar</a>
    </div>

</form>